replicaCount: 2

image:
  repository: httpd
  tag: "2.4"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
