apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-effort-apache
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: max-effort-apache

  template:
    metadata:
      labels:
        app: max-effort-apache

    spec:
      containers:
        - name: max-effort-apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
